### ISSUE TITLE
Conflicting name in OpenRepos

### ISSUE THREAD

**Issue by direc85** [AsteroidOS/starship#16]
Hi,

Now that [Sailfish OS 4.2.0.21 has been released](https://blog.jolla.com/verla/), and we are inching closer to an actual release that could reach OpenRepos, there unfortunately already exists an application called [Starfish](https://openrepos.net/content/jgressmann/starfish) (`harbour-starfish`). I reckon we have to change the name to something else.

My initial proposition is **Watchfish** (`harbour-watchfish`) as there exists `libwatchfish` for SailfishOS in the repository already, so it would fit the naming nicely.

**Comment by FlorentRevest** [comment]
`libwatchfish` is actually not asteroid-specific. It is an open-source component we re-use from another developer https://github.com/piggz/libwatchfish
I'd rather not steal their name :) 

I'm not good at naming things but here are a few other proposals: (please, anyone reading this propose idea or vote so that we can decide on the best option later) around the theme of sailing and astronomy (luckily celestial bodies were used to navigate at night for centuries so I used this as an inspiration):

- Astrolabe
- Almanac
- Azimuth
- Arcminute (not only sailing, space but also time :p )
- Ephemeris
- Equinox
- Polaris
- Ecliptic
- Penumbra
- Astrarium
- Alidade
- Backstaff
- Octant
- Sextant
- Quadrant
- Kamal
- Tide

The Ubuntu Touch client is named Telescope and I like the analogy that it is used to look at an asteroid (watch) :) 

Please let me know if you have preferences.

**Comment by direc85** [comment]
Well in that case, better not cause confusion with `watchfish` and `libwatchfish`!

I immediately liked **Astrarium** due to its resemblance of Asteroid, but...

Telescope sure works well for the purpose! After a quick search I found **Aquascope** ([pic](https://en.wikipedia.org/wiki/Aquascope)) which would continue that trend nicely!

Also, the name doesn't _have_ to end in a "-fish"! (My personal opinion is that there are too many fishes in the package names already...)

**Comment by jrtberlin** [comment]
We could name it "Starship". A ship to sail space :D

**Comment by FlorentRevest** [comment]
Aquascope would work quite well as a parallel to telescope but I wonder what we would be left with for a potential KDE mobile client :p

I think I prefer starship. It also has a nerdy connotation which is appropriate :)

**Comment by direc85** [comment]
I'd prefer Aquascope, but I can't deny the coolness factor of Starship!

**Comment by jrtberlin** [comment]
I think Starship is more inline with our general space theme and we don't run out of names for plasma mobile and ios.

**Comment by GeoffTearle** [comment]
+1 for Starship!

**Comment by Am2per** [comment]
Astrofish?
and also +1 for Starship!

**Comment by haelge** [comment]
What about "Periscope"? It's like the other way round, observing sth. from underwater. However it is somewhat related to warships.

Another idea would be "Neptune". A bigger  celestial object than an asteroid.

Giuseppe Piazzi discovered the asteroid ceres. Possible Nicknames could be "Pino", "Beppe" or "Peppino"

"Kuiper" as in kuiper belt, a circumstellar disc similar to the asteroid belt.

And last but not least, to go full nerd: "Mediator" someone who manages the communication and interaction between two parties AND the name of a mon calamari star cruiser developed by the mon calamari, an amphibic life form in star wars.

**Comment by ncartron** [comment]
Periscope makes me think about the (now dead?) Twitter's live video service.

I like both Telescope and Aquascope

**Comment by robthebold** [comment]
I do love most of these names, but the idea just stuck me: "Vela". It's a Southern sky constellation and Latin for "sail".

**Comment by haelge** [comment]
I like "Vela". I'd generaly prefer a rather short name, that has an association to an astronomic and naval theme but without these something-fish or sail-something. patterns.
